const images = {
  logo: require("../image/logo.png"),
  noImage: require("../image/noImage.png"),
  video: require("../image/video.png"),
  backgroundHeader: require("../image/background.png"),
  fea1: require("../image/fea1.png"),
  fea2: require("../image/fea2.png"),
  fea3: require("../image/fea3.png"),
  prod1: require("./prod1.png"),
  prod2: require("./prod2.png"),
  prod3: require("./prod3.png"),
  prod4: require("./prod4.png"),
  service1: require("./services1.png"),
  service2: require("./services2.png"),
  service3: require("./services3.png"),
  reason: require("./reason.png"),
  proj1: require("./proj1.png"),
  proj2: require("./proj2.png"),
  proj3: require("./proj3.png"),
  proj4: require("./proj4.png"),
  proj5: require("./proj5.png"),
  proj6: require("./proj6.png"),
  listSer1: require("./listSer1.png"),
  listSer2: require("./listSer2.png"),
  listSer3: require("./listSer3.png"),
  listSer4: require("./listSer4.png"),
  listSer5: require("./listSer5.png"),
  listSer6: require("./listSer6.png"),
  media: require("./media.png"),
  fb: require("./fb.png"),
  tw: require("./tw.png"),
  ig: require("./ig.png"),
};

export default images;
